export const ADD_NEW_STUDENT = "ADD_NEW_STUDENT"
export const EDIT_CURRENT_STUDENT = "EDIT_CURRENT_STUDENT"
export const DELETE_STUDENT = "DELETE_STUDENT"
export const CHANGE_STUDENT_TABLE = "CHANGE_STUDENT_TABLE"

export const ADD_NEW_CLASS = "ADD_NEW_CLASS"
export const EDIT_CLASS =  "EDIT_CLASS"
export const DELETE_CLASS = "DELETE_CLASS"
export const CHANGE_CLASS_TABLE = "CHANGE_CLASS_TABLE"

export const ADD_NEW_SECTION = "ADD_NEW_SECTION"
export const EDIT_SECTION = "EDIT_SECTION"
export const DELETE_SECTION = "DELETE_SECTION"
export const CHANGE_SECTION_TABLE = "CHANGE_SECTION_TABLE"